# Generated by Django 6.0.7 on 2026-07-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        (
            "clients",
            "0010_invoicecredit_expires_at_invoicecredit_internal_note_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("code", models.SlugField(max_length=80)),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("vendor", "Vendor"),
                            ("photographer", "Photographer"),
                            ("partner", "Partner"),
                            ("team_member", "Team member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referrer_name", models.CharField(max_length=150)),
                ("visits", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_attribution",
                        to="clients.clientsession",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_attribution",
                        to="clients.lead",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.photographerprofile",
                    ),
                ),
                (
                    "referral_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="dashboard.referrallink",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("lumispixel", "LumisPixel"),
                            ("external", "External (manual)"),
                        ],
                        default="lumispixel",
                        max_length=20,
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=80)),
                ("reviewer_name", models.CharField(max_length=150)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="growth_reviews",
                        to="clients.client",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="clients.client",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="referrallink",
            constraint=models.UniqueConstraint(
                fields=("photographer", "code"), name="unique_referral_code_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="growth_review_rating_1_5",
            ),
        ),
    ]
