# Generated by Django 6.0.7 on 2026-07-31 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        (
            "clients",
            "0010_invoicecredit_expires_at_invoicecredit_internal_note_and_more",
        ),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("campaign_type", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("channel", models.CharField(blank=True, max_length=80)),
                ("tracking_link", models.URLField(blank=True)),
                (
                    "spend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="reviewrequest",
            options={"ordering": ["-requested_at"]},
        ),
        migrations.AddField(
            model_name="referrallink",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_links",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referrallink",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_requests",
                to="clients.clientsession",
            ),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="message",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="sent",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="reviewrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False)),
                fields=("photographer", "booking"),
                name="unique_review_request_per_booking",
            ),
        ),
        migrations.AddField(
            model_name="growthcampaign",
            name="photographer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.photographerprofile",
            ),
        ),
        migrations.AddField(
            model_name="referrallink",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_links",
                to="dashboard.growthcampaign",
            ),
        ),
    ]
