# Generated by Django 6.0.7 on 2026-08-01 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("dashboard", "0002_growthcampaign_alter_reviewrequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitation_email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("studio_manager", "Studio Manager"),
                            ("photographer", "Photographer"),
                            ("assistant", "Assistant"),
                            ("editor", "Editor"),
                        ],
                        default="photographer",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("invited", "Invited"),
                            ("invitation_expired", "Invitation expired"),
                            ("inactive", "Inactive"),
                            ("access_suspended", "Access suspended"),
                        ],
                        default="invited",
                        max_length=24,
                    ),
                ),
                ("primary_location", models.CharField(blank=True, max_length=150)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "On assignment"),
                            ("limited", "Limited"),
                            ("away", "Away"),
                            ("not_configured", "Not configured"),
                        ],
                        default="not_configured",
                        max_length=24,
                    ),
                ),
                ("current_assignment", models.CharField(blank=True, max_length=180)),
                ("invitation_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="studio_memberships",
                        to="accounts.photographerspecialty",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.photographerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("studio", "user"),
                        name="unique_studio_user_membership",
                    )
                ],
            },
        ),
    ]
