# Generated by Django 6.0.7 on 2026-08-02 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_studio_invitation_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studiomembership",
            name="additional_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studiomembership",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studiomembership",
            name="internal_title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="studiomembership",
            name="time_zone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="studiomembership",
            name="working_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studiomembership",
            name="working_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studiomembership",
            name="working_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StudioMembershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_membership_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_events",
                        to="dashboard.studiomembership",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
