# Generated by Django 6.0.7 on 2026-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_studiomembership_additional_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studiomembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("studio_manager", "Studio Manager"),
                    ("photographer", "Photographer"),
                ],
                default="photographer",
                max_length=24,
            ),
        ),
    ]
