# Generated by Django 6.1 on 2026-08-09 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("dashboard", "0006_alter_studiomembership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("blocked", "Blocked Time"),
                            ("editing", "Editing Time"),
                            ("vacation", "Vacation"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("blocks_booking", models.BooleanField(default=False)),
                ("entire_team", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="schedule_constraints",
                        to="dashboard.studiomembership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedule_constraints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_constraints",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="schedule_constraint_positive_interval",
                    )
                ],
            },
        ),
    ]
