# Generated by Django 6.0.7 on 2026-07-28 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("clients", "0006_alter_clientactivity_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="galleries/covers/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("review", "Review"),
                            ("ready", "Ready"),
                            ("published", "Published"),
                            ("delivered", "Delivered"),
                            ("archived", "Archived"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("password", "Password protected"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("image_count", models.PositiveIntegerField(default=0)),
                ("favorite_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "storage_used",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Storage used in bytes."
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="clients.client",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["photographer", "status", "-created_at"],
                        name="gallery_owner_status_created",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("photographer", "slug"),
                        name="gallery_owner_slug_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__isnull", True),
                            ("published_at__isnull", True),
                            ("expires_at__gt", models.F("published_at")),
                            _connector="OR",
                        ),
                        name="gallery_expiry_after_publish",
                    ),
                ],
            },
        ),
    ]
