# Generated by Django 6.0.7 on 2026-07-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0002_galleryphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("client_only", "Client Only"),
                            ("hidden", "Hidden"),
                        ],
                        default="client_only",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="galleries/albums/covers/%Y/%m/"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_for_albums",
                        to="galleries.galleryphoto",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="galleries.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AlbumPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_photos",
                        to="galleries.album",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_memberships",
                        to="galleries.galleryphoto",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "added_at"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="albums",
                through="galleries.AlbumPhoto",
                to="galleries.galleryphoto",
            ),
        ),
        migrations.AddIndex(
            model_name="albumphoto",
            index=models.Index(
                fields=["album", "position"], name="album_photo_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="albumphoto",
            constraint=models.UniqueConstraint(
                fields=("album", "photo"), name="album_photo_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["gallery", "visibility", "display_order"],
                name="album_gallery_visibility_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                fields=("gallery", "name"), name="album_gallery_name_unique"
            ),
        ),
    ]
