# Generated by Django 6.0.7 on 2026-07-29 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0003_album_albumphoto_album_photos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("last_access_at", models.DateTimeField(blank=True, null=True)),
                ("resent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="galleries.gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["-invited_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="galleries.galleryinvitation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_gallery", models.BooleanField(default=True)),
                ("download_images", models.BooleanField(default=True)),
                ("download_originals", models.BooleanField(default=False)),
                ("favorite_photos", models.BooleanField(default=True)),
                ("comment", models.BooleanField(default=False)),
                ("share_gallery", models.BooleanField(default=True)),
                ("purchase_prints", models.BooleanField(default=False)),
                ("automatic_gallery_lock", models.BooleanField(default=False)),
                ("download_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "watermark",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("preview", "Preview Only"),
                            ("all", "All Images"),
                        ],
                        default="preview",
                        max_length=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gallery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="galleries.gallery",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="galleryinvitation",
            constraint=models.UniqueConstraint(
                fields=("gallery", "email"), name="gallery_invitation_email_unique"
            ),
        ),
    ]
