# Generated by Django 6.0.7 on 2026-07-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0004_galleryinvitation_accesstoken_gallerypermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GallerySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studio_logo",
                    models.ImageField(
                        blank=True, upload_to="galleries/branding/%Y/%m/"
                    ),
                ),
                ("accent_color", models.CharField(default="#B42328", max_length=7)),
                (
                    "watermark_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("top_left", "Top left"),
                            ("top_right", "Top right"),
                            ("bottom_left", "Bottom left"),
                            ("bottom_right", "Bottom right"),
                        ],
                        default="bottom_right",
                        max_length=20,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("editorial", "Editorial"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("allow_downloads", models.BooleanField(default=True)),
                ("allow_original_downloads", models.BooleanField(default=False)),
                ("zip_downloads", models.BooleanField(default=True)),
                ("download_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("enable_favorites", models.BooleanField(default=True)),
                ("enable_comments", models.BooleanField(default=False)),
                ("enable_slideshow", models.BooleanField(default=True)),
                ("show_exif_data", models.BooleanField(default=False)),
                ("show_file_names", models.BooleanField(default=False)),
                ("gallery_url", models.SlugField(max_length=220)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gallery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="galleries.gallery",
                    ),
                ),
            ],
        ),
    ]
