# Generated by Django 6.0.7 on 2026-07-29 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("galleries", "0006_gallerystore_galleryorder_storeproduct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("photographer", "Photographer"),
                            ("client", "Client"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("gallery_created", "Gallery created"),
                            ("gallery_updated", "Gallery updated"),
                            ("gallery_published", "Gallery published"),
                            ("gallery_archived", "Gallery archived"),
                            ("photos_uploaded", "Photos uploaded"),
                            ("photos_deleted", "Photos deleted"),
                            ("album_created", "Album created"),
                            ("album_updated", "Album updated"),
                            ("ai_started", "AI processing started"),
                            ("ai_completed", "AI processing completed"),
                            ("client_invited", "Client invited"),
                            ("client_viewed", "Client viewed gallery"),
                            ("client_favorited", "Client favorited a photo"),
                            ("client_commented", "Client commented"),
                            ("photo_downloaded", "Photo downloaded"),
                            ("gallery_downloaded", "Gallery downloaded"),
                            ("gallery_shared", "Gallery shared"),
                            ("store_order_created", "Store order created"),
                            ("payment_changed", "Payment status changed"),
                            ("permission_changed", "Permission changed"),
                            ("settings_changed", "Settings changed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("related_object_type", models.CharField(blank=True, max_length=40)),
                ("related_object_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="galleries.gallery",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_activity",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["photographer", "gallery", "-created_at"],
                        name="activity_owner_gallery_date",
                    ),
                    models.Index(
                        fields=["gallery", "event_type", "-created_at"],
                        name="activity_gallery_type_date",
                    ),
                ],
            },
        ),
    ]
