# Generated by Django 6.0.7 on 2026-07-29 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("galleries", "0007_galleryactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Opaque, application-generated identifier only.",
                        max_length=64,
                    ),
                ),
                ("session_identifier", models.CharField(blank=True, max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "Gallery view"),
                            ("photo_view", "Photo view"),
                            ("download", "Photo download"),
                            ("gallery_download", "Full gallery download"),
                            ("favorite", "Favorite"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "device_category",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=24)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "authenticated_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="galleries.gallery",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_analytics_events",
                        to="accounts.photographerprofile",
                    ),
                ),
                (
                    "related_album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="galleries.album",
                    ),
                ),
                (
                    "related_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="galleries.galleryphoto",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["photographer", "gallery", "-occurred_at"],
                        name="analytics_owner_gallery_date",
                    ),
                    models.Index(
                        fields=["gallery", "event_type", "-occurred_at"],
                        name="analytics_gallery_type_date",
                    ),
                    models.Index(
                        fields=["gallery", "visitor_identifier", "-occurred_at"],
                        name="analytics_gallery_visitor",
                    ),
                ],
            },
        ),
    ]
