# Generated by Django 6.0.7 on 2026-07-29 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("galleries", "0008_galleryanalyticsevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="archive_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("completed", "Project Completed"),
                    ("expired", "Gallery Expired"),
                    ("client_requested", "Client Requested"),
                    ("storage", "Storage Management"),
                    ("duplicate", "Duplicate Gallery"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_galleries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft-deletion marker used before permanent removal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("uploading", "Uploading"),
                    ("processing", "Processing"),
                    ("review", "Review"),
                    ("ready", "Ready"),
                    ("published", "Published"),
                    ("delivered", "Delivered"),
                    ("archived", "Archived"),
                    ("expired", "Expired"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="retention_type",
            field=models.CharField(
                choices=[
                    ("indefinite", "Retained Indefinitely"),
                    ("until_date", "Retained Until Date"),
                    ("scheduled", "Scheduled for Deletion"),
                    ("deletion_pending", "Deletion Pending"),
                ],
                default="indefinite",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="retention_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="scheduled_deletion_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GalleryArchivePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archive_delivered", models.BooleanField(default=False)),
                ("archive_after_expiration", models.BooleanField(default=True)),
                ("inactivity_days", models.PositiveIntegerField(blank=True, null=True)),
                ("default_retention_days", models.PositiveIntegerField(default=365)),
                ("warn_before_deletion", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_archive_policy",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
        ),
    ]
