# Generated by Django 6.0.7 on 2026-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_studiomembership_role"),
        ("galleries", "0009_gallery_archive_reason_gallery_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="assigned_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_galleries",
                to="dashboard.studiomembership",
            ),
        ),
    ]
