# Generated by Django 5.2 on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0025_gallerystoragedeletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryphoto",
            name="multipart_upload",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo",
                to="galleries.gallerymultipartupload",
            ),
        ),
    ]
