# Generated by LumisPixel authentication foundation.

import uuid
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_specialties(apps, schema_editor):
    Specialty = apps.get_model("accounts", "PhotographerSpecialty")
    for name in ["Portrait", "Wedding", "Event", "Sports", "Street", "Graduation", "Family", "Commercial", "Real Estate", "Fashion", "Product", "Corporate"]:
        slug = name.lower().replace(" ", "-")
        Specialty.objects.get_or_create(slug=slug, defaults={"name": name, "is_active": True})


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("primary_role", models.CharField(choices=[("client", "Client"), ("photographer", "Photographer")], default="client", max_length=20)),
                ("last_active_workspace", models.CharField(choices=[("client", "Client"), ("photographer", "Photographer"), ("marketplace", "Marketplace"), ("operations", "Operations")], default="client", max_length=20)),
                ("account_status", models.CharField(choices=[("pending_email_verification", "Pending email verification"), ("active", "Active"), ("restricted", "Restricted"), ("suspended", "Suspended"), ("deactivated", "Deactivated"), ("scheduled_for_deletion", "Scheduled for deletion")], default="pending_email_verification", max_length=40)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("required_password_reset", models.BooleanField(default=False)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("privacy_policy_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("groups", models.ManyToManyField(blank=True, related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"ordering": ["email"]},
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile_image", models.ImageField(blank=True, null=True, upload_to="client-profiles/")),
                ("phone_number", models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number using digits, spaces, parentheses, hyphens, and an optional leading +.", regex="^\\+?[0-9().\\-\\s]{7,20}$")])),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("marketplace_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="client_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PhotographerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(blank=True, max_length=150)), ("display_name", models.CharField(blank=True, max_length=150)), ("slug", models.SlugField(max_length=180, unique=True)),
                ("profile_image", models.ImageField(blank=True, null=True, upload_to="photographer-profiles/")), ("cover_image", models.ImageField(blank=True, null=True, upload_to="photographer-covers/")),
                ("biography", models.TextField(blank=True)), ("phone_number", models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number using digits, spaces, parentheses, hyphens, and an optional leading +.", regex="^\\+?[0-9().\\-\\s]{7,20}$")])),
                ("city", models.CharField(blank=True, max_length=100)), ("state", models.CharField(blank=True, max_length=100)), ("service_area", models.CharField(blank=True, max_length=255)), ("website_url", models.URLField(blank=True)),
                ("years_of_experience", models.PositiveSmallIntegerField(blank=True, null=True)), ("accepts_marketplace_requests", models.BooleanField(default=False)),
                ("verification_status", models.CharField(choices=[("not_started", "Not started"), ("draft", "Draft"), ("submitted", "Submitted"), ("under_review", "Under review"), ("additional_information_required", "Additional information required"), ("approved", "Approved"), ("rejected", "Rejected"), ("suspended", "Suspended"), ("expired", "Expired")], default="not_started", max_length=45)),
                ("verification_submitted_at", models.DateTimeField(blank=True, null=True)), ("verified_at", models.DateTimeField(blank=True, null=True)), ("verification_expires_at", models.DateTimeField(blank=True, null=True)),
                ("onboarding_step", models.CharField(blank=True, max_length=80)), ("onboarding_completed", models.BooleanField(default=False)), ("payout_setup_completed", models.BooleanField(default=False)), ("public_profile_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="photographer_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["display_name", "business_name"]},
        ),
        migrations.CreateModel(
            name="PhotographerSpecialty",
            fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("slug", models.SlugField(max_length=100, unique=True)), ("is_active", models.BooleanField(default=True)), ("photographers", models.ManyToManyField(blank=True, related_name="specialties", to="accounts.photographerprofile"))],
            options={"verbose_name_plural": "photographer specialties", "ordering": ["name"]},
        ),
        migrations.AddConstraint(model_name="user", constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("email"), name="accounts_user_email_lower_unique")),
        migrations.RunPython(seed_specialties, migrations.RunPython.noop),
    ]
