# Generated by Django 6.0.7 on 2026-07-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_repair_missing_profile_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="marketplace_enabled",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="marketing_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="client-profiles/"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
