# Generated by Django 6.0.7 on 2026-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_clientprofile_marketplace_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photographerprofile",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="photographerprofile",
            name="website_url",
        ),
        migrations.RemoveField(
            model_name="photographerspecialty",
            name="photographers",
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="business_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photographer_profiles/logos/"
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="business_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("studio", "Studio")],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="default_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photographer_profiles/photos/"
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                related_name="photographer_profiles",
                to="accounts.photographerspecialty",
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="website_theme",
            field=models.CharField(
                choices=[
                    ("elegant", "Elegant"),
                    ("modern", "Modern"),
                    ("sports", "Sports"),
                ],
                default="elegant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="willing_to_travel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
