# Generated by Django 6.0.7 on 2026-07-18 05:49

from django.db import migrations, models


def normalize_photographer_onboarding_step(apps, schema_editor):
    PhotographerProfile = apps.get_model("accounts", "PhotographerProfile")
    mapping = {
        "": 1,
        "welcome": 1,
        "business_information": 1,
        "profile": 2,
        "specialties": 3,
        "business": 4,
        "theme": 5,
    }
    for profile in PhotographerProfile.objects.all().only("pk", "onboarding_step"):
        raw = profile.onboarding_step
        try:
            step = int(raw)
        except (TypeError, ValueError):
            step = mapping.get(raw, 1)
        if step not in {1, 2, 3, 4, 5}:
            step = 1
        profile.onboarding_step = str(step)
        profile.save(update_fields=["onboarding_step"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_seed_photographer_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(normalize_photographer_onboarding_step, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="photographerprofile",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
