# Generated by Django 6.0.7 on 2026-07-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_clientprofile_onboarding_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photographerprofile",
            name="available_internationally",
            field=models.BooleanField(
                default=False,
                help_text="Available for assignments outside the photographer's home country.",
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="available_nationally",
            field=models.BooleanField(
                default=False,
                help_text="Available for assignments throughout the photographer's home country.",
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="destination_photographer",
            field=models.BooleanField(
                default=False,
                help_text="Accepts assignments that require travel outside the normal service area.",
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="travel_radius",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (10, "10 miles"),
                    (25, "25 miles"),
                    (50, "50 miles"),
                    (100, "100 miles"),
                    (250, "250 miles"),
                ],
                help_text="Maximum routine travel distance from the primary business location, in miles.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photographerprofile",
            name="service_area",
            field=models.CharField(
                blank=True,
                help_text="Legacy free-text service area retained for historical review; new onboarding uses structured travel fields.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="photographerprofile",
            name="willing_to_travel",
            field=models.BooleanField(
                default=False,
                help_text="Whether this photographer accepts assignments beyond their primary city/service base.",
            ),
        ),
    ]
