# Generated by Django 6.0.7 on 2026-07-18 09:56

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_photographerprofile_available_internationally_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photographerprofile",
            name="website_theme",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("elegant", "Elegant"),
                    ("modern_studio", "Modern Studio"),
                    ("cinematic", "Cinematic"),
                    ("portfolio_editorial", "Portfolio Editorial"),
                    ("sports_events", "Sports & Events"),
                ],
                default="basic",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PhotographerWebsiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.accounts.models.photographer_website_hero_upload_path,
                    ),
                ),
                ("theme_content", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_profile",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotographerWebsiteProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.accounts.models.photographer_website_project_upload_path,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.photographerwebsiteprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
