# Generated by Django 6.1 on 2026-08-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_photographerprofile_website_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('region_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocationDatasetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=64)),
                ('country_count', models.PositiveIntegerField(default=0)),
                ('region_count', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-imported_at',),
            },
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='administrative_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profiles', to='accounts.administrativeregion'),
        ),
        migrations.AddField(
            model_name='administrativeregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_regions', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='country_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profiles', to='accounts.country'),
        ),
    ]
