# Generated by Django 6.1 on 2026-08-30 07:13

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_SECTIONS = {
    'basic': ('frame', ['hero', 'portfolio', 'contact']),
    'elegant': ('narrative', ['hero', 'services', 'about', 'portfolio', 'stats', 'reviews', 'contact']),
    'modern_studio': ('panorama', ['hero', 'services', 'about', 'portfolio', 'reviews', 'contact']),
    'cinematic': ('monograph', ['hero', 'about', 'services', 'portfolio', 'reviews', 'contact']),
    'portfolio_editorial': ('collective', ['hero', 'portfolio', 'about', 'team', 'reviews', 'contact']),
    'sports_events': ('atelier', ['hero', 'services', 'stats', 'portfolio', 'reviews', 'team', 'contact']),
}


def create_default_website_sections(apps, schema_editor):
    WebsiteProfile = apps.get_model('accounts', 'PhotographerWebsiteProfile')
    WebsiteSection = apps.get_model('accounts', 'PhotographerWebsiteSection')
    for website in WebsiteProfile.objects.select_related('photographer_profile').iterator():
        theme = website.photographer_profile.website_theme
        slug, sections = DEFAULT_SECTIONS.get(theme, DEFAULT_SECTIONS['basic'])
        WebsiteSection.objects.bulk_create([
            WebsiteSection(photographer_website=website, section_type=section, layout_variant=f'{slug}-{section}', display_order=index)
            for index, section in enumerate(sections)
        ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_administrativeregion_country_locationdatasetimport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerprofile',
            name='website_theme',
            field=models.CharField(choices=[('basic', 'Frame'), ('elegant', 'Narrative'), ('modern_studio', 'Panorama'), ('cinematic', 'Monograph'), ('portfolio_editorial', 'Collective'), ('sports_events', 'Atelier')], default='basic', max_length=32),
        ),
        migrations.CreateModel(
            name='PhotographerWebsiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=40)),
                ('layout_variant', models.CharField(blank=True, max_length=80)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.photographerwebsiteprofile')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('photographer_website', 'section_type'), name='unique_photographer_website_section_type')],
            },
        ),
        migrations.RunPython(create_default_website_sections, migrations.RunPython.noop),
    ]
