# Generated by Django 6.1 on 2026-08-31

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0012_alter_photographerprofile_website_theme_and_more")]

    operations = [
        migrations.CreateModel(
            name="PhotographerWebsiteEquipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to=apps.accounts.models.photographer_website_equipment_upload_path)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("photographer_website", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment_items", to="accounts.photographerwebsiteprofile")),
            ],
            options={"ordering": ["display_order", "id"]},
        ),
    ]
