# Generated by Django 5.x

import django.conf
import django.db.models.deletion
import uuid
from django.db import migrations, models

import apps.internal_ops.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ("internal_ops", "0005_system_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(default=apps.internal_ops.models.approval_reference, editable=False, max_length=16, unique=True)),
                ("kind", models.CharField(choices=[("ai_credits", "AI credit adjustment"), ("plan_override", "Plan or entitlement override"), ("account_restriction", "Account restriction"), ("employee_access", "Employee access change"), ("data_export", "Sensitive data export"), ("other", "Other sensitive action")], max_length=32)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("cancelled", "Cancelled"), ("executed", "Executed")], default="pending", max_length=16)),
                ("title", models.CharField(max_length=180)),
                ("reason", models.TextField()),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("proposed_changes", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approver_department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approval_requests", to="internal_ops.department")),
                ("requester", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approval_requests", to="internal_ops.employeeprofile")),
                ("requester_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="internal_approval_requests", to=django.conf.settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approval_reviews", to="internal_ops.employeeprofile")),
                ("reviewed_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="internal_approval_reviews", to=django.conf.settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(model_name="approvalrequest", index=models.Index(fields=["status", "risk_level", "created_at"], name="approval_state_risk_idx")),
        migrations.AddIndex(model_name="approvalrequest", index=models.Index(fields=["approver_department", "status"], name="approval_dept_state_idx")),
        migrations.AddIndex(model_name="approvalrequest", index=models.Index(fields=["target_type", "target_id"], name="approval_target_idx")),
    ]
