# Generated by Django 6.0.7 on 2026-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("clients", "0002_clientinvoice_clientsession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="last_contacted_date",
            new_name="last_contacted_at",
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_contacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="lost_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_follow_up",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["photographer", "next_follow_up"], name="lead_owner_followup"
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_value__gte", 0),
                    ("estimated_value__isnull", True),
                    _connector="OR",
                ),
                name="lead_estimated_value_nonnegative",
            ),
        ),
    ]
