# Generated by Django 6.0.7 on 2026-07-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_expand_lead_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_created", "Lead created"),
                    ("note_added", "Note added"),
                    ("email_sent", "Email sent"),
                    ("consultation_scheduled", "Consultation scheduled"),
                    ("lead_converted", "Lead converted"),
                    ("contract_signed", "Contract signed"),
                    ("invoice_sent", "Invoice sent"),
                    ("payment_received", "Payment received"),
                    ("gallery_delivered", "Gallery delivered"),
                    ("lead_updated", "Lead updated"),
                    ("stage_changed", "Stage changed"),
                    ("follow_up_created", "Follow-up created"),
                    ("lead_booked", "Lead booked"),
                    ("lead_lost", "Lead lost"),
                    ("lead_archived", "Lead archived"),
                ],
                max_length=32,
            ),
        ),
    ]
