# Generated by Django 6.0.7 on 2026-07-28 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("clients", "0004_lead_archived_at_alter_clientactivity_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual"),
                    ("business", "Business"),
                    ("organization", "Organization"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("text", "Text message"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="profile_photo",
            field=models.ImageField(
                blank=True, upload_to="clients/profile_photos/%Y/%m/"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["photographer", "-created_at"], name="client_owner_created"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["photographer", "client_type"], name="client_owner_type"
            ),
        ),
    ]
