# Generated by Django 6.0.7 on 2026-07-31 04:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("clients", "0008_clientsession_booking_value_invoicepayment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=255)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("package", "Booking package"),
                            ("session", "Session fee"),
                            ("deposit", "Deposit"),
                            ("add_on", "Add-on"),
                            ("travel", "Travel fee"),
                            ("product", "Prints or products"),
                            ("custom", "Custom item"),
                        ],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "due_date"],
            },
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="clients.clientsession",
            ),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="client_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="delivery_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="discount_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="invoice_number",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="payment_terms",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="tax_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="clientinvoice",
            constraint=models.UniqueConstraint(
                fields=("photographer", "invoice_number"),
                name="invoice_owner_number_unique",
            ),
        ),
        migrations.AddField(
            model_name="invoiceactivity",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="clients.clientinvoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceactivity",
            name="photographer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.photographerprofile",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="clients.clientinvoice",
            ),
        ),
        migrations.AddField(
            model_name="invoicepaymentschedule",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule",
                to="clients.clientinvoice",
            ),
        ),
    ]
