# Generated by Django 6.0.7 on 2026-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("clients", "0009_invoiceactivity_invoicelineitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicecredit",
            name="expires_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicecredit",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoicecredit",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoicecredit",
            name="reason",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoicecredit",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoicecredit",
            name="submission_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="external_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("bank_transfer", "Bank transfer"),
                    ("cash", "Cash"),
                    ("check", "Check"),
                    ("external", "External payment"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="processor_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="submission_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="reason",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="submission_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="invoicecredit",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_amount__gte", 0)),
                name="credit_remaining_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicecredit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("remaining_amount__lte", models.F("original_amount"))
                ),
                name="credit_remaining_not_over_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicecredit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_key", ""), _negated=True),
                fields=("photographer", "submission_key"),
                name="credit_owner_submission_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicepayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_key", ""), _negated=True),
                fields=("photographer", "submission_key"),
                name="payment_owner_submission_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_key", ""), _negated=True),
                fields=("photographer", "submission_key"),
                name="refund_owner_submission_unique",
            ),
        ),
    ]
