# Generated by Django 6.0.7 on 2026-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_clientsession_confirmed_at"),
        ("dashboard", "0006_alter_studiomembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="assigned_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_clients",
                to="dashboard.studiomembership",
            ),
        ),
        migrations.AddField(
            model_name="clientsession",
            name="assigned_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_bookings",
                to="dashboard.studiomembership",
            ),
        ),
    ]
