# Generated by Django 6.1 on 2026-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_clientactivity_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="lead_source",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
