# Generated by Django 6.1 on 2026-08-09 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_client_lead_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientactivity",
            options={
                "ordering": ["-occurred_at", "-pk"],
                "verbose_name_plural": "client activities",
            },
        ),
        migrations.AddField(
            model_name="clientnote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientnote",
            name="content",
            field=models.TextField(max_length=5000),
        ),
    ]
