# Generated by Django 6.1 on 2026-08-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_alter_clientactivity_options_clientnote_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientactivity",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="clients.clientsession",
            ),
        ),
        migrations.AddField(
            model_name="clientsession",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="clientsession",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientsession",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="clientactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_created", "Lead created"),
                    ("note_added", "Note added"),
                    ("email_sent", "Email sent"),
                    ("consultation_scheduled", "Consultation scheduled"),
                    ("lead_converted", "Lead converted"),
                    ("contract_signed", "Contract signed"),
                    ("invoice_sent", "Invoice sent"),
                    ("payment_received", "Payment received"),
                    ("gallery_delivered", "Gallery delivered"),
                    ("lead_updated", "Lead updated"),
                    ("stage_changed", "Stage changed"),
                    ("follow_up_created", "Follow-up created"),
                    ("lead_booked", "Lead booked"),
                    ("lead_lost", "Lead lost"),
                    ("lead_archived", "Lead archived"),
                    ("client_updated", "Client updated"),
                    ("client_archived", "Client archived"),
                    ("client_restored", "Client restored"),
                    ("booking_created", "Booking created"),
                    ("booking_updated", "Booking updated"),
                    ("booking_rescheduled", "Booking rescheduled"),
                    ("booking_cancelled", "Booking cancelled"),
                ],
                max_length=32,
            ),
        ),
    ]
