# Generated by Django 6.1 on 2026-08-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("clients", "0016_clientactivity_booking_and_more"),
        ("dashboard", "0007_scheduleconstraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsession",
            name="event_kind",
            field=models.CharField(
                choices=[("booking", "Booking"), ("consultation", "Consultation")],
                default="booking",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MiniSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("starts_at", models.DateTimeField()),
                ("slot_duration_minutes", models.PositiveSmallIntegerField()),
                ("slot_count", models.PositiveSmallIntegerField()),
                ("buffer_minutes", models.PositiveSmallIntegerField(default=0)),
                ("capacity_per_slot", models.PositiveSmallIntegerField(default=1)),
                ("location", models.CharField(max_length=255)),
                ("service", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_mini_sessions",
                        to="dashboard.studiomembership",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="MiniSessionSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mini_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="clients.minisession",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="MiniSessionSlotBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mini_session_bookings",
                        to="clients.client",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.photographerprofile",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="clients.minisessionslot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="minisessionslot",
            name="clients",
            field=models.ManyToManyField(
                related_name="mini_session_slots",
                through="clients.MiniSessionSlotBooking",
                to="clients.client",
            ),
        ),
        migrations.AddIndex(
            model_name="minisession",
            index=models.Index(
                fields=["photographer", "status", "starts_at"],
                name="mini_owner_status_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="minisessionslotbooking",
            constraint=models.UniqueConstraint(
                fields=("slot", "client"), name="mini_slot_client_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="minisessionslot",
            constraint=models.UniqueConstraint(
                fields=("mini_session", "position"),
                name="mini_slot_parent_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="minisessionslot",
            constraint=models.UniqueConstraint(
                fields=("mini_session", "starts_at"),
                name="mini_slot_parent_start_unique",
            ),
        ),
    ]
