# Generated by Django 6.1 on 2026-08-10 01:55

import apps.clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_alter_contractevent_event_type_contractsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractsignature",
            name="signed_snapshot",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.CreateModel(
            name="SignedContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        storage=apps.clients.models.contract_document_storage,
                        upload_to=apps.clients.models.signed_contract_document_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "file_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "signed_content_hash",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_document",
                        to="clients.contract",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "updated_at"], name="signed_doc_status_time"
                    )
                ],
            },
        ),
    ]
