# Generated by Django 6.1 on 2026-08-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0021_contractsignature_signed_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("customized", "Customized"),
                    ("sent", "Sent"),
                    ("resent", "Resent"),
                    ("viewed", "Viewed"),
                    ("signed", "Signed"),
                    ("pdf_generated", "PDF generated"),
                ],
                max_length=24,
            ),
        ),
    ]
