# Generated by Django 6.1 on 2026-08-15 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_photographerprofile_website_theme_and_more'),
        ('clients', '0022_contract_activity_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('customized', 'Customized'), ('sent', 'Sent'), ('resent', 'Resent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('photographer_signed', 'Photographer signed'), ('pdf_generated', 'PDF generated')], max_length=24),
        ),
        migrations.CreateModel(
            name='ContractPhotographerSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('signature_value', models.CharField(max_length=200)),
                ('consent_accepted', models.BooleanField()),
                ('consent_text', models.TextField()),
                ('signed_at', models.DateTimeField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('contract_version', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='photographer_signature', to='clients.contract')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photographer_contract_signatures', to='accounts.photographerprofile')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photographer_contract_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
