# Generated by Django 6.0.7 on 2026-07-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_alter_photographerprofile_website_theme_and_more"),
        ("galleries", "0002_galleryphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("face_detection", "Face Detection"),
                            ("face_clustering", "Face Clustering"),
                            ("duplicate_detection", "Duplicate Detection"),
                            ("blur_detection", "Blur Detection"),
                            ("closed_eyes_detection", "Closed Eyes Detection"),
                            ("image_quality_scoring", "Image Quality Scoring"),
                            ("scene_recognition", "Scene Recognition"),
                            ("object_detection", "Object Detection"),
                            ("color_detection", "Color Detection"),
                            ("keyword_generation", "Keyword Generation"),
                            ("search_indexing", "Search Indexing"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reserved for a future background-worker task id.",
                        max_length=255,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=5)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_summary", models.CharField(blank=True, max_length=300)),
                ("error_details", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("worker_metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to="galleries.gallery",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to="accounts.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProcessingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_images", models.PositiveIntegerField(default=0)),
                ("completed_images", models.PositiveIntegerField(default=0)),
                ("failed_images", models.PositiveIntegerField(default=0)),
                ("current_stage", models.CharField(blank=True, max_length=120)),
                (
                    "heartbeat_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Future workers can use this to report liveness.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="ai_engine.aijob",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI processing statuses",
            },
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["photographer", "status", "-queued_at"],
                name="ai_job_owner_status",
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["gallery", "task_type", "status"], name="ai_job_gallery_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprocessingstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_images__lte", models.F("total_images"))),
                name="ai_completed_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprocessingstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(("failed_images__lte", models.F("total_images"))),
                name="ai_failed_lte_total",
            ),
        ),
    ]
